# Generated by Django 4.2.20 on 2025-04-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter_app', '0002_order_driver_order_status_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
