# Generated by Django 4.2.20 on 2025-04-10 12:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='createmodelm',
            managers=[
                ('cheap_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
