# Generated by Django 4.2.20 on 2025-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_createproductlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_salary', models.IntegerField()),
                ('emp_no', models.IntegerField()),
                ('emp_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='createmodelm',
            managers=[
            ],
        ),
    ]
